### ISSUE TITLE
debugging  /build/dev-server.js  ERROR

### ISSUE THREAD

**Issue by tear3333** [epicmaxco/epic-spinners#12]
ERROR  Failed to compile with 21 errors10:09:33
output.js:103
 error  in ./src/components/lib/HollowDotsSpinner.vue
output.js:103
output.js:103
Module build failed: Error: 
output.js:103
Vue packages version mismatch:
- vue@2.5.16
- vue-template-compiler@2.5.9
This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
    at Object.<anonymous> (d:\nodejs\epic-spinners-master\node_modules\vue-template-compiler\index.js:8:9)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by smartapant** [comment]
@tear3333 thanks, we will check that!
