### ISSUE TITLE
Unit tests failed

### ISSUE THREAD

**Issue by yarkovaleksei** [epicmaxco/epic-spinners#13]
For unit tests i use Jest and vue-test-utils.
Test error:
```
 FAIL  src/components/ui/Preloader/Preloader.spec.ts
  ● Test suite failed to run

    /home/user/git/frontend/node_modules/epic-spinners/src/lib.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import HollowDotsSpinner from './components/lib/HollowDotsSpinner.vue'
                                                                                             ^^^^^^
    
    SyntaxError: Unexpected token import

    
      
      at ScriptTransformer._transformAndBuildScript (node_modules/jest-cli/node_modules/jest-runtime/build/script_transformer.js:396:17)
      at Object.<anonymous> (src/components/ui/Preloader/script.ts:1098:72)
```
Test code:
```
import { mount } from '@vue/test-utils'
import Preloader from './Preloader.vue'

let wrapper: any

describe('ui/Preloader.vue', () => {
  beforeEach(() => {
    wrapper = mount(Preloader, {
      attachToDocument: true
    })
  })

  it('should render correct contents', () => {
    expect(wrapper.classes()).toContain('preloader')
    expect(wrapper.find('.semipolar-spinner')).toBe(true)
    expect(wrapper.findAll('.semipolar-spinner > div.ring').length).toBe(5)
  })
})
```
Component wrapper template:
```
<template>
  <div class="preloader">
    <semipolar-spinner
      :animation-duration="duration"
      :size="size"
      :color="color"
    />
  </div>
</template>
```

**Comment by judgeyboy** [comment]
Hi @yarkovaleksei 
I just stumbled across this issue and was able to fix it by adding to the jest config file:
```
transformIgnorePatterns: [
    "node_modules/(?!epic-spinners)"
  ],
```
I hope it helps.
Here some more info from Jest docs about `transformIgnorePatterns`:

> Sometimes it happens (especially in React Native or TypeScript projects) that 3rd party modules are published as untranspiled. Since all files inside node_modules are not transformed by default, Jest will not understand the code in these modules, resulting in syntax errors. To overcome this, you may use transformIgnorePatterns to whitelist such modules.

**Comment by matthieusb** [comment]
Same problem here. I have tried the fix by @judgeyboy but it is not working.
Is there anything else to configure ? Did you do add anything else to your project ?

Thanks in advance for your help.

**Comment by matthieusb** [comment]
Adding the right preset seemed to do the trick:

```
preset: 'ts-jest/presets/js-with-ts'
```

**Comment by asvae** [comment]
It would make more sense to ship transpiled components + chunk them to get tree shaking.

Moved to #32

**Comment by tokidoki11** [comment]
got the same error but on different thing

```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import HollowDotsSpinner from './components/lib/HollowDotsSpinner.vue'
                                                                                                    ^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

```

**Comment by tokidoki11** [comment]
I change my import to 
`importd FulfillingBouncingCircleSpinner from 'epic-spinners/src/components/lib/FulfillingBouncingCircleSpinner.vue` 
and added this to my jest config
```
transformIgnorePatterns: [
    "node_modules/(?!epic-spinners)"
  ],
```

Error became
```
  export default {
    ^^^^^^

    SyntaxError: Unexpected token export
```
